export const securities: string[] = ['VOD LN Equity',
  'BARC LN Equity',
  'BMW GR Equity',
  'AAL LN Equity',
  'GOOGL US Equity',
  'MSFT US Equity',
  'TEAM US Equity',
  'CRM US Equity',
  'JPM US Equity',
  'FB US Equity',
  'AMZN US Equity',
  'AAPL US Equity',
  'BABA US Equity',
  'TICK Index',
  'NTES US Equity',
  'KHC US Equity',
  'NFLX US Equity',
  'TSCO LN Equity'];
